### ISSUE TITLE
Meaning of the model's output

### ISSUE THREAD

**Issue by 249498576** [Rocky1salady-killer/DGE-GM#1]
Sorry to bother you. 
I'd like to know the meaning of '**_gaze_bias_**' in the '**_GazeSwinTransformer_**' in the '**_model.py_**'. 
Looking forward to your reply.

**Comment by Rocky1salady-killer** [comment]
Thank you for your interest in our work!

Gaze_bias can be interpreted as representing the uncertainty or confidence level in the gaze estimation. A larger gaze_bias value might indicate that the model has lower confidence in its gaze estimation, while a smaller value suggests a higher confidence level. 
Therefore, this information is valuable for downstream applications as it provides insights into the predictability and reliability of the model's estimations.

**Comment by 249498576** [comment]
Thank you very much for your answer!
Your code and explanations have been very helpful to me.
Best wishes for your research success!
